version: "3.9"
services:
  blog:
    build:
      context: .              # Build from the current directory
    volumes:
      - .:/usr/src/app        # Mount project directory
      - /usr/src/app/node_modules # Exclude node_modules from being overwritten
    ports:
      - "3000:3000"           # Map port 3000 to localhost
    environment:
      NODE_ENV: development   # Set environment for development
    command: yarn start --host 0.0.0.0